---

consul_datacenter: dc1
consul_data_dir: /opt/consul
consul_client_addr: 0.0.0.0
consul_ui: yes
consul_server: yes
consul_bootstrap_expect: 3
consul_encrypt: "GEZzRM+2P+FiUcyrx9Fte8NbwtTlX3NA"
consul_bind_addr: "{{ ansible_eth1.ipv4.address }}"
consul_retry_join:
  - "{{ hostvars[groups['consulservers'][0]].ansible_eth1.ipv4.address }}"
