#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
      register: terraform

    - name: add consul servers to inventory
      add_host:
        name: "{{ item }}"
        groups: consulservers
      loop: "{{ terraform.outputs.consul_servers.value }}"

- name: setup consul-servers
  hosts: all
  become: yes
  gather_facts: no
  remote_user: root

  pre_tasks:
    - name: pause
      pause:
        seconds: 60

    - name: wait for the host to be available
      wait_for:
        port: 22

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.update
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp

- name: setup consul-server-0
  hosts: consul-server-0.meinit.nl
  become: yes
  gather_facts: yes
  remote_user: root

  roles:
    - role: robertdebock.consul

- name: setup non consul-server-0
  hosts: all:!consul-server-0.meinit.nl
  become: yes
  gather_facts: yes
  remote_user: root

  roles:
    - role: robertdebock.consul
